version: '2'
services:
  postgres:
    container_name: clair_postgres
    image: docker.io/dockerskoleni/postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    image: docker.io/dockerskoleni/clair:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - /var/lib/clair_config:/config
    command: [-config, /config/config.yaml]
